config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  resources :fortunes
  root "fortunes#index"
  get "random", to: "fortunes#random"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fortune.rb
class Fortune < ApplicationRecord
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  def index
    @allfortunes = Fortune.all
  end
  def show
    @fortune = Fortune.find(params[:id])
  end
  def random
    @randfortune = Fortune.find(Fortune.pluck(:id).sample)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/views/fortunes/index.html.erb
<html>
  <head>
    <title> Your Better Fortune Cookie </title>
    <link rel="icon" href="<%= asset_path('fortune_cookie.png') %>" type="image/png">
  </head>
<h1>Your Better Fortune</h1>
<div id="pick_one">
  <%= button_to "Random", random_path, method: :get%>
</div>
<div id="fortunes">
<% @allfortunes.find_each do |fortune| %>
  <p> 
  <%= link_to "Fortune #{fortune.id}", fortune %>
  </p>
<% end %>  
</div>

app/views/fortunes/random.html.erb
<h1><%= @randfortune.text %> </h1>

app/views/fortunes/show.html.erb
<h1><%= @fortune.text %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Fortunecookie" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>